# -*- coding: utf-8 -*-
"""DataCleaningBNB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTat73fKm2hKDLVtEATgeI8fxLSrCWcb
"""

!pip install pandas

import pandas as pd
import re

# Function to clean ingredients
def clean_ingredients(ingredient_list):
    # Remove content within parentheses
    ingredient_list = re.sub(r'\([^)]*\)', '', ingredient_list)
    # Remove quantities (e.g., 1 tablespoon, 3 tablespoon, 2 teaspoons, etc.)
    ingredient_list = re.sub(r'\b\d+\s*\w*\b', '', ingredient_list)
    # Remove extra spaces and commas
    ingredient_list = re.sub(r'\s+', ' ', ingredient_list).strip()
    ingredient_list = re.sub(r'\s*,\s*', ',', ingredient_list)
    # Remove backslashes
    ingredient_list = ingredient_list.replace('\\', '')
    return ingredient_list

# Function to clean the Cleaned-Ingredients column
def clean_cleaned_ingredients(ingredient_list):
    # Remove content within parentheses
    ingredient_list = re.sub(r'\([^)]*\)', '', ingredient_list)
    # Remove extra spaces and commas
    ingredient_list = re.sub(r'\s+', ' ', ingredient_list).strip()
    ingredient_list = re.sub(r'\s*,\s*', ',', ingredient_list)
    # Remove backslashes
    ingredient_list = ingredient_list.replace('\\', '')
    return ingredient_list

# Function to clean the TranslatedIngredients column
def clean_translated_ingredients(ingredient_list):
    # Remove content within parentheses
    ingredient_list = re.sub(r'\([^)]*\)', '', ingredient_list)
    # Remove quantities (e.g., 1 tablespoon, 3 tablespoon, 2 teaspoons, etc.)
    ingredient_list = re.sub(r'\b\d+\s*\w*\b', '', ingredient_list)
    # Remove extra spaces and commas
    ingredient_list = re.sub(r'\s+', ' ', ingredient_list).strip()
    ingredient_list = re.sub(r'\s*,\s*', ',', ingredient_list)
    # Remove unnecessary slashes and hyphens
    ingredient_list = re.sub(r'[-/]', '', ingredient_list)
    # Remove leading and trailing commas
    ingredient_list = ingredient_list.strip(',')
    # Remove backslashes
    ingredient_list = ingredient_list.replace('\\', '')
    return ingredient_list

# Function to clean the TranslatedRecipeName column
def clean_recipe_name(recipe_name):
    # Remove content within parentheses
    recipe_name = re.sub(r'\([^)]*\)', '', recipe_name)
    # Remove extra spaces
    recipe_name = re.sub(r'\s+', ' ', recipe_name).strip()
    # Remove backslashes and forward slashes
    recipe_name = recipe_name.replace('\\', '').replace('/', '')
    recipe_name = recipe_name.replace('-', 'or')

    return recipe_name

# Read the CSV file
df =pd.read_csv('/Cleaned_Indian_Food_Dataset.csv')

# Apply the cleaning functions to the respective columns
df['TranslatedIngredients'] = df['TranslatedIngredients'].apply(clean_translated_ingredients)
df['Cleaned-Ingredients'] = df['Cleaned-Ingredients'].apply(clean_cleaned_ingredients)
df['TranslatedRecipeName'] = df['TranslatedRecipeName'].apply(clean_recipe_name)

# Save the updated DataFrame back to a CSV file
df.to_csv('updated_file.csv', index=False)

from google.colab import drive
drive.mount('/content/drive')

"""# New section"""